services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dat-ia-api
    ports:
      - "8000:8000"
    environment:
      APP_ENV: development
      USE_CLOUDFLARE_LLM: "true"
      GOOGLE_API_KEY: "${GOOGLE_API_KEY}"
      # GOOGLE_API_KEY: # Tu key acá
      CLOUDFLARE_ACCOUNT_ID: "${CLOUDFLARE_ACCOUNT_ID}"
      CLOUDFLARE_API_KEY: "${CLOUDFLARE_API_KEY}"
      USE_LANGSMITH_TRACING: "${USE_LANGSMITH_TRACING:-false}"
      LANGSMITH_API_KEY: "${LANGSMITH_API_KEY:-}"
      LANGSMITH_PROJECT: "${LANGSMITH_PROJECT:-dat-ia-test}"
      LANGSMITH_TRACING_SAMPLING_RATE: "${LANGSMITH_TRACING_SAMPLING_RATE:-1.0}"
    volumes:
      # Esto crea una carpeta local llamada .hf_cache y la conecta a la caché del contenedor
      - ./.hf_cache:/app/.cache/huggingface
      - ./chroma_data:/app/chroma_db
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
