apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dat-ia-chroma
  labels:
    app.kubernetes.io/name: dat-ia-api
    app.kubernetes.io/part-of: dat-ia
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
